Refactored so that each party may have multiple keys.
Trust-Machines/frost pull request #33
Opened 2022-12-20 15:33 UTC by a3slade

This allows one party to hold multiple keys. It uses one polynomial & one nonce/ephemeral key for the party since a party with multiple keys would be able to combine that information anyways.

I am new to rust and not sure if I'm doing the book-keeping in the best way. I would appreciate some feedback on that regards, especially wrt the best structures for what we will eventually be doing with the p2p.

https://github.com/Trust-Machines/frost/issues/31

2022-12-21 09:16 UTC, netrome commented on src/main.rs
> +    key_owners: &Vec<usize>, // N-long vector with indices = key_id and values = party_id
```suggestion
    key_owners: &[usize], // N-long vector with indices = key_id and values = party_id
```

2022-12-21 09:16 UTC, netrome commented on src/main.rs
> +        }
Yes, in this case I'd recommend using the `extend` method. We also don't need to call `.drain()` since we want to consume `pks` and HashMap implements `IntoIterator`. (Assuming hashbrowns HashMap works the same way as the one in std).
```suggestion
        public_keys.extend(pks);
```

2022-12-21 09:16 UTC, netrome commented on src/main.rs
> +    key_owners: &Vec<usize>,
```suggestion
    key_owners: &[usize],
```

2022-12-21 09:16 UTC, netrome commented on src/main.rs
> +            party_id: party_id.clone(),
`party_id` is a reference to a usize, and should not need to be cloned. I assume the need here is to deference it.
```suggestion
            party_id: *party_id,
```

Another option would be to pattern match on it in line 106 as |&party_id|.

2022-12-21 09:16 UTC, netrome commented on src/frost.rs
> +    pub public_key: HashMap<usize, Point>, // key is key_id
This map of keys `HashMap<usize, Point>` is repeated a lot in the code. I suggest adding a type alias or wrapping it in a new type to improve readability.

Either:
```
type KeyMap = HashMap<usize, Point>;
```
or
```
struct KeyMap(HashMap<usize, Point>);
```

2022-12-21 09:16 UTC, netrome commented on src/frost.rs
> +    pub public_key: HashMap<usize, Point>, // key is key_id
In the latter case, this crate can be helpful to make things more ergonomic: https://crates.io/crates/derive_more

2022-12-21 09:31 UTC, netrome commented
I added some general recommendations and nit comments. Otherwise I think it looks good, all types should be easy to serialize for the p2p communication. I might ofc be missing something since this is all very new to me.

2022-12-21 23:25 UTC, a3slade commented on src/frost.rs
> +    pub public_key: HashMap<usize, Point>, // key is key_id
I picked the first option & did the same for the private keys and set of signers.

2022-12-21 23:26 UTC, a3slade commented
@netrome Thank you!

2022-12-22 08:55 UTC, netrome approved these changes

2022-12-23 06:14 UTC, xoloki requested changes
I made some non cryptographic asks in this review.  I'll leave the greater crytographic and protocol suggestions for another review, possibly after merge.

2022-12-23 06:14 UTC, xoloki commented on src/frost.rs
>          // TODO: How should we handle bad As?
We shouldn't have to handle them.  In real usage, we won't create a SA unless we have the correct number of commitments.

2022-12-23 06:14 UTC, xoloki commented on src/frost.rs
>  fn get_B_rho_R_vec(
Let's fix this now.  Maybe `compute_intermediate_values`?

2022-12-24 01:49 UTC, a3slade commented on src/frost.rs
> +    pub fn get_shares(&self) -> Vec<(usize, Scalar)> {
tbh, I don't remember why I went with a vector instead of a hash map. Probably because I knew those returned values were immediately going to be serialized and I thought maybe that was the closest.

Does the serialization work like pickle (from python) or does everything need to get parsed?

On the filtering side, I'm think that each party with have to go through each other party's shares and pull out ('from', shares[key_id]) for each of their key_ids which would be O(1) either way I would think. I was assuming that the 'from' would be contained in the header or something and didn't need to be included here. The tuple being sent is ('to', share). I didn't know a slick way of doing that. Did you have a suggestion for how to easily do the filtering that I'm not seeing?

2022-12-24 01:56 UTC, a3slade commented on src/frost.rs
>          // TODO: How should we handle bad As?
I'm guessing that my comment was in reference to the assert after that which checks the schnorr proof.

If stackers are going to commit to a polynomials when they sign up to stack, then we should do that before they are allotted their slots/key_ids so I agree that doesn't need to be handled here.

I'll remove the comment but leaving the check. We'll need to remember to handle that elsewhere.

2022-12-24 01:57 UTC, a3slade commented on src/frost.rs
>  fn get_B_rho_R_vec(
sure. definitely an improvement.

2023-01-06 05:38 UTC, xoloki commented
Closing in favor of #40 which puts everything into v2.

2023-01-06 05:38 UTC, closed without merging